[build]
  command = "npm install && npm run build"
  publish = "src/public"

[dev]
  command = "npm run dev"
  port = 8888

[[redirects]]
  from = "/*"
  to = "/index.js"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
